### ISSUE TITLE
Duplicate errors reported (missing metadata in one)

### ISSUE THREAD

**Issue by apexskier** [bugsnag/bugsnag-react#6]
### Expected behavior
A single exception is reported when an error is thrown on component mount.

### Observed behavior
Two exceptions are reported. One is missing react metadata.

### Steps to reproduce
In testing, I throw an error in the `componentDidMount` somewhere under the `ErrorBoundary` created with `bugsnag-react`. In my before notify handler I print out the errors that pass through with `console.error(report.errorClass, report.errorMessage, report.metaData)`.

In the console I see:

![screen shot 2018-01-23 at 16 46 31](https://user-images.githubusercontent.com/329222/35308538-00abed4c-005d-11e8-9b2f-6e7a29b3978d.png)

(`fullstory` is custom metadata we're adding)

Note that the first error doesn't have `react` in the metadata, but the second does. This is reflected in the bugsnag app.

![screen shot 2018-01-23 at 16 49 01](https://user-images.githubusercontent.com/329222/35308622-592c3b70-005d-11e8-8242-b7891c65acd3.png)

### Version
`bugsnag-js`: 4.3.1
`bugsnag-react`: 1.0.0

**Comment by bengourley** [comment]
Hi – this is a known issue, but fortunately it only appears when React is in development mode. Can you confirm that switching to the prod build of React fixes it?

In development React errs on the side of rethrowing errors so that nothing gets swallowed, resulting in the same error being caught by the error boundary but then also caught by window.onerror.

**Comment by apexskier** [comment]
Yep, the prod build only reports once, with correct metadata. Thanks for the explanation!
