### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by apexskier** [bugsnag/bugsnag-react#7]
It appears that `bugsnag-react` doesn't have typing information ([`bugsnag-js` does](https://github.com/bugsnag/bugsnag-js/tree/master/types)).

I'm not sure exactly how you'd like to manage the typing information, but here's a declaration file I've written for my project. I'm not sure if it should expose the `formatComponentStack`, but this matches how the module is written, I think.

```ts
declare module "bugsnag-react" {
    import { IPlugin } from "bugsnag-js/types/client";
    import * as React from "react";

    const createPlugin: (react: typeof React) => IPlugin
    export default createPlugin;
    export const formatComponentStack: (str: string) => string;
}
```

**Comment by luisgarciaalanis** [comment]
Thanks man 👍

**Comment by jhaenchen** [comment]
Would love to see this published as @types/bugsnag-react @bengourley or in this package as bugsnag-react.d.ts, though I'm not sure if that's a file you would prefer to be dynamically generated as part of your build process

**Comment by MaxGabriel** [comment]
Just ran into this issue

**Comment by bengourley** [comment]
Hi @jhaenchen. I'm intrigued by your mention of "dynamically generated" – we've struggled with types falling out of date when the library changes (with bugsnag-node and bugsnag-js) and so part of the reason we didn't add this yet was because we want to accompany it with a good way of ensuring the correctness/accuracy of the types. So far our best idea is to write the tests in TypeScript, but I'd be interested to hear more about dynamically generating the .d.ts files if it possible?

**Comment by karol-majewski** [comment]
In case you'd like to have `ErrorBoundary` component typed:

```diff
  declare module 'bugsnag-react' {
    import { IPlugin } from 'bugsnag-js/types/client';
+   import { BeforeSend } from 'bugsnag-js/types/common';
    import * as React from 'react';

    const createPlugin: (react: typeof React) => IPlugin;
    export default createPlugin;
    export const formatComponentStack: (str: string) => string;

+  interface Props {
+    beforeSend?: BeforeSend;
+    FallbackComponent?: React.ComponentType<{
+      error: Error;
+      info: React.ErrorInfo;
+    }>;
+  }
+
+  export type ErrorBoundary = React.ComponentType<Props>;
  }
```

Ideally, these types would work out of the box with:

https://github.com/bugsnag/bugsnag-js/blob/7071fe484c6650f1731c2b99c5af368c18bf16a6/types/client.d.ts#L19

**Comment by sampsonjoliver** [comment]
@bengourley The only real way you're gonna dynamically generate types is by rewriting the source in Typescript (or Flow) and compiling with type outputs. Which is only arduous in terms of the build pipeline, given there's only one file to be rewritten 😂 

But if that's not feasible, getting @karol-majewski's types up in DefinitelyTyped and versioned according to the `bugsnag-react` release they are written for would be ideal. You don't want to provide third-party types as though they were first-party because then your users can't opt-out of having a compile error in their code.

**Comment by bengourley** [comment]
We just shipped our new ["universal" JS notifier](https://github.com/bugsnag/bugsnag-js/) and with that a new version of [this plugin](https://github.com/bugsnag/bugsnag-js/tree/master/packages/plugin-react) which is now `@bugsnag/plugin-react` on npm.

TypeScript support has been improved for the plugin interface exported by that module, but we still need to do something to get the custom `ErrorBoundary`'s types in there. I have an internal roadmap ticket for that and this repo is now deprecated so I'm going to close this off.
